
api: 
  
  artifactId: "proc-claims-orch-v1-dev"
  version: "1.0.0"
  majorVersion: "v1"
  port: "8082"
  
# api Configurations
"sysclaims":
  "host": "sys-claims-cms.us-e2.cloudhub.io"
  "basepath": "/api"
  "path": "/claims/performanceData"
  "getmethod": "GET"
  "statuspath": "/status"  
  "port" : "443"
  "contenttype": "application/json"
  "x-correlation-id": "abcdedf09-nkn4546-jn34nkkm-fg669c0002"
  "clientId": "12234"
  "clientSecret": "1234"
  "orchestration-type": "value"
  
# reconnection configuration
"retries":
  "frequency": "1000"
  "attempts": "3"
  "timeout": "400000" 
  
tls.keystore:
 type: "pkcs12"
 alias: "server"
 path: "certs/proc-claims-cms-dev.p12"
 
jks.keystore:
 password: "mulesoft"
 type: "jks"
 path: "certs/keystore.jks" 
  
"autodiscovery":
  "id": "17512639"

